# -*- coding: utf-8 -*-
"""data_agu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17mJ8g6609DBcPjYTJVRgy3iHW1V-apSJ
"""

from google.colab import drive
drive.mount('/content/drive')

import imgaug.augmenters as iaa
import cv2
import os

# Define the augmentation sequence
seq = iaa.Sequential([
    iaa.Fliplr(0.5),  # horizontal flips
    iaa.Flipud(0.5),  # vertical flips
    iaa.CropAndPad(percent=(-0.1, 0.1), pad_mode="constant"),  # random crops and pads
    iaa.Crop(percent=(0, 0.1)),  # random crops
    iaa.GaussianBlur(sigma=(0, 3.0)),  # gaussian blur
    iaa.ContrastNormalization((0.75, 1.5)),  # contrast normalization
    iaa.Affine(rotate=(-45, 45)),  # random rotations
    iaa.Affine(scale={"x": (0.8, 1.2), "y": (0.8, 1.2)}),  # scaling
    iaa.Affine(translate_percent={"x": (-0.2, 0.2), "y": (-0.2, 0.2)}),  # translation
    iaa.Affine(shear=(-16, 16)) , # shearing
    iaa.Multiply((0.5, 1.5), per_channel=0.5),  # brightness changes
    iaa.GammaContrast((0.5, 2.0))  # gamma and contrast changes
])

# Path to the directory containing the images
input_dir = "/content/drive/MyDrive/dom/min_data"
# Path to the directory where augmented images will be saved
output_dir = "/content/drive/MyDrive/dom/max_data"

# Ensure output directory exists, create if not
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# Loop through each image in the input directory
for filename in os.listdir(input_dir):
    if filename.endswith(".jpg") or filename.endswith(".png"):
        image_path = os.path.join(input_dir, filename)
        img = cv2.imread(image_path)  # Read the image
        images_aug = [seq(image=img) for _ in range(10)]  # Apply augmentation sequence
        # Save augmented images to output directory
        for i, image_aug in enumerate(images_aug):
            output_path = os.path.join(output_dir, f"{filename.split('.')[0]}_{i}.jpg")
            cv2.imwrite(output_path, image_aug)